version: "3"
services: 
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 3000:3000
    volumes: 
      - /app/node_modules
      - .:/app
    # command: [npm]    